(function(root){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format((n||0)/100);
 const labels={keep:'Je le garde',compare:'Comparer les offres',cancel:'Résiliation à préparer',requested:'Résiliation demandée'};
 let current=null,district='charges',busy=false;
 function model(d,period){
  const ops=(d.operations||[]).filter(o=>!period||o.date.startsWith(period)),choices=d.campaign_choices||{};
  const items=(d.recurrences||[]).filter(r=>r.active).map(r=>{
   const op=(d.operations||[]).find(o=>o.series===r.name||o.merchant===r.name||r.name.startsWith(o.merchant+' / '));
   return {...r,key:'charge:'+r.name,category:op?.category};
  }).filter(r=>['Abonnements','Frais bancaires','Assurances'].includes(r.category)).sort((a,b)=>Number(b.category!=='Assurances')-Number(a.category!=='Assurances')||b.annual-a.annual);
  const decisions=Object.entries(choices).filter(([,v])=>v?.choice),done=decisions.length,level=done>=6?3:done>=3?2:1;
  return {items,choices,decisions,done,level,next:level===1?3:level===2?6:null,potential:items.filter(r=>!choices[r.key]?.choice).reduce((s,r)=>s+r.annual,0),income:ops.filter(o=>o.kind==='income').reduce((s,o)=>s+o.amount,0),loan:-ops.filter(o=>o.amount<0&&/Crédits/.test(o.category)).reduce((s,o)=>s+o.amount,0),period};
 }
 function scene(type,level){
  const ground='<ellipse cx="150" cy="180" rx="128" ry="25" fill="#314f3f" opacity=".13"/><path d="M28 158 Q150 105 272 158 L260 184 Q150 226 40 184Z" fill="#a8c5a1"/><path d="M40 184 Q150 222 260 184 L260 194 Q150 232 40 194Z" fill="#769676"/>';
  const tree='<g fill="#638767"><rect x="54" y="117" width="7" height="49" rx="3" fill="#9c7856"/><circle cx="57" cy="107" r="22"/><circle cx="44" cy="119" r="18"/><circle cx="69" cy="123" r="19"/></g>';
  const flag=level>1?'<path d="M226 130V65" stroke="#466355" stroke-width="4"/><path d="M228 65h34l-10 12 10 12h-34Z" fill="#dc865d"/>':'';
  const objects={coffre:'<path d="M92 105Q150 53 211 105V165H92Z" fill="#ca9b55"/><path d="M92 115H211V164H92Z" fill="#dcaf66"/><path d="M111 88V169M190 88V169" stroke="#f6d99c" stroke-width="12"/><rect x="143" y="112" width="22" height="27" rx="5" fill="#f9e5b9"/><circle cx="154" cy="123" r="4" fill="#796840"/><circle cx="226" cy="160" r="13" fill="#ebc76e"/><path d="M222 154h8m-8 6h8" stroke="#9f874c" stroke-width="2"/>',charges:'<path d="M91 87h111v88H91Z" fill="#f5e8ce"/><path d="M78 90l26-37h88l27 37Z" fill="#cf785a"/><path d="M87 91h121v17H87Z" fill="#f0b781"/><path d="M87 91h17v18H87Zm34 0h17v18h-17Zm34 0h17v18h-17Zm34 0h19v18h-19Z" fill="#fff4d8"/><rect x="133" y="129" width="29" height="46" rx="14" fill="#5b7c68"/><rect x="101" y="123" width="21" height="24" rx="3" fill="#a9c4ae"/><rect x="173" y="123" width="21" height="24" rx="3" fill="#a9c4ae"/><path d="M134 69h27" stroke="#fae7c5" stroke-width="4"/>',credits:'<path d="M85 166V90h44v76m43 0V90h44v76" fill="#b4bab0"/><path d="M82 84h50v17H82Zm87 0h50v17h-50Z" fill="#d7d8c5"/><path d="M107 103Q150 70 194 103v13Q150 86 107 116Z" fill="#e5d9b7"/><path d="M113 180Q151 137 190 180" fill="none" stroke="#f3ead3" stroke-width="24"/><path d="M91 84V73m22 11V73m67 11V73m22 11V73" stroke="#b4bab0" stroke-width="10"/>'};
  return `<svg viewBox="0 0 300 230" aria-hidden="true">${ground}${tree}${objects[type]}${flag}<path d="M73 185l9-5m137-1l12 3" stroke="#f5e6b4" stroke-width="5" stroke-linecap="round"/></svg>`;
 }
 function route(){
  const hash=location.hash||'#overview',accounts=!['#overview','#progress','#play'].includes(hash);
  const book=document.getElementById('account-book'),map=document.getElementById('campaign'),progress=document.getElementById('campaign-progress');
  if(book)book.hidden=!accounts;if(map)map.hidden=accounts||hash==='#progress';if(progress)progress.hidden=accounts||hash!=='#progress';
  document.querySelectorAll('[data-view-link]').forEach(a=>a.setAttribute('aria-current',(accounts?a.hash==='#ledger':a.hash===(hash==='#play'?'#overview':hash))?'page':'false'));
 }
 function render(d,period,chart){
  const host=document.getElementById('campaign');if(!host)return;
  current=model(d,period);const m=current,lv=['','Prendre la main','Faire de la place','Garder le cap'][m.level];
  const tile=(id,title,sub)=>`<button class="district ${district===id?'selected':''}" data-district="${id}" aria-pressed="${district===id}"><span class="district-scene">${scene(id,m.level)}</span><span class="district-title">${title}</span><span class="district-sub">${sub}</span></button>`;
  host.innerHTML=`<div class="campaign-heading"><div><span class="campaign-kicker">TA CAMPAGNE PERSONNELLE</span><h2>Un peu plus libre.<br><em>Un choix à la fois.</em></h2><p>Moins de charges subies. Plus de place pour tes projets.</p></div><div class="campaign-medal"><span>CHAPITRE</span><b>0${m.level}</b><strong>${lv}</strong></div></div><div class="territory"><div class="territory-caption"><span>LE TERRITOIRE DE TES FINANCES</span><span>✦ ${m.done} choix enregistré${m.done>1?'s':''}</span></div><div class="districts">${tile('coffre','Le coffre','Ta cible : 10 % pour toi')}${tile('charges','L’atelier des charges',m.items.length+' charges à passer en revue')}${tile('credits','Le pont des crédits','Préparer la sortie')}</div><p class="map-note">Choisis un lieu pour avancer · les fanions apparaissent après trois décisions.</p></div><div id="district-panel" tabindex="-1"></div><div class="campaign-foot"><span>Une courte partie suffit. Reviens quand tu veux.</span><a href="#progress">Voir ma progression →</a></div>`;
  panel();
  const p=document.getElementById('campaign-progress');
  p.innerHTML=`<div class="campaign-kicker">TON CHEMIN PARCOURU</div><h2>Chaque choix laisse une trace.</h2><p>Les chapitres racontent tes décisions. Les économies, elles, devront être confirmées par tes relevés.</p><div class="milestones">${[['Premier choix',m.done>=1],['Atelier ouvert · 3 choix',m.done>=3],['Cap maintenu · 6 choix',m.done>=6]].map(([t,b])=>`<div class="milestone ${b?'earned':''}"><span>${b?'✦':'◇'}</span><strong>${t}</strong><small>${b?'Débloqué':'À découvrir'}</small></div>`).join('')}</div><div class="campaign-meter"><span>${m.next?m.done+' / '+m.next+' décisions pour le prochain chapitre':'Tous les chapitres de cette version explorés'}</span><progress max="${m.next||m.done||1}" value="${m.done}"></progress></div><h3>Ton argent au fil des mois</h3><p class="small">Ressources en vert · sorties en orange · cible d’épargne en bleu. Les mois aux extrémités peuvent être incomplets.</p>${chart||''}<h3>Ton carnet de décisions</h3><div class="decision-log">${m.decisions.map(([key,v])=>`<div><span><strong>${esc(v.name)}</strong><small>${labels[v.choice]||''} · ${esc((v.updated_at||'').slice(0,10).split('-').reverse().join('/'))}</small></span><button class="secondary" data-choice="" data-key="${esc(key)}">Revoir</button></div>`).join('')||'<p>Ton premier choix apparaîtra ici. Rien à rattraper, tu commences où tu en es.</p>'}</div><p class="small">Aucune économie confirmée par ce carnet. « Résiliation demandée » est une déclaration, pas une preuve d’arrêt des prélèvements.</p>`;
  bind(host);bind(p);route();
 }
 function panel(){
  const m=current,host=document.getElementById('district-panel');if(!host||!m)return;
  if(district==='coffre')host.innerHTML=`<div class="district-intro"><span class="campaign-kicker">LE COFFRE</span><h3>Donner une destination à ton argent.</h3><p>Ta cible pour la période : <strong>${money(Math.max(0,m.income)*.1)}</strong>, soit 10 % des ressources.</p></div><div class="chapter-card"><span class="big-symbol">◇</span><div><h3>La première pièce du coffre</h3><p>Ajoute les relevés de tes livrets sur le PC pour mesurer ton épargne réelle. Le coffre se remplira à partir de ces données.</p><a class="button" href="#mission">Voir mon épargne</a></div></div>`;
  else if(district==='credits')host.innerHTML=`<div class="district-intro"><span class="campaign-kicker">LE PONT DES CRÉDITS</span><h3>Voir le chemin jusqu’au dernier remboursement.</h3><p><strong>${money(m.loan)}</strong> de remboursements repérés sur la période sélectionnée.</p></div><div class="chapter-card"><span class="big-symbol">↗</span><div><h3>Dessiner la ligne d’arrivée</h3><p>Le capital restant dû et la date de fin manquent encore. Sans eux, une jauge de remboursement serait trompeuse. Prépare le dernier échéancier de ton prêt pour construire cette étape.</p><a class="button secondary" href="#ledger">Retrouver mes remboursements</a></div></div>`;
  else{
   const pending=m.items.filter(r=>!m.choices[r.key]?.choice).slice(0,3);
   host.innerHTML=`<div class="district-intro"><div><span class="campaign-kicker">L’ATELIER DES CHARGES</span><h3>Qu’est-ce qui mérite de rester ?</h3><p>Trois choix maximum. Garder une dépense utile est aussi une bonne décision.</p></div><span class="potential">${money(m.potential)}<small>/an à examiner · pas une économie acquise</small></span></div><div class="action-deck">${pending.map(r=>`<article class="action-card"><span class="action-type">${esc(r.category)}</span><h4>${esc(r.name.replace(/^PRLV SEPA /,''))}</h4><div class="annual-cost">${money(r.annual)}<small>/an</small></div><p>${money(r.amount)} · fréquence ${esc(r.frequency.toLowerCase())}. Coût annualisé au dernier montant observé.</p><div class="action-buttons"><button data-choice="keep" data-key="${esc(r.key)}">Je garde</button><button class="secondary" data-choice="compare" data-key="${esc(r.key)}">Je compare</button>${r.category==='Abonnements'?`<button class="text-button" data-choice="cancel" data-key="${esc(r.key)}">Je prépare la résiliation →</button>`:''}</div></article>`).join('')||'<div class="chapter-card"><span class="big-symbol">✦</span><div><h3>L’atelier est à jour.</h3><p>Retrouve tes décisions dans Ma progression. De nouvelles charges pourront apparaître au prochain relevé.</p><a href="#progress" class="button">Voir mon parcours</a></div></div>'}</div><div class="next-actions">${m.decisions.filter(([,v])=>['compare','cancel'].includes(v.choice)).map(([key,v])=>`<div><span><strong>${esc(v.name)}</strong><small>${v.choice==='cancel'?'À faire auprès du fournisseur : demander la résiliation.':'À faire : demander une offre comparable, garanties et frais compris.'}</small></span>${v.choice==='cancel'?`<button class="secondary" data-choice="requested" data-key="${esc(key)}">J’ai envoyé la demande</button>`:`<a class="button secondary" href="#progress">Mon carnet</a>`}</div>`).join('')}</div><p class="small">Détection au dernier relevé. Aucun contrat n’est modifié par l’application.</p>`;
  }
 }
 function bind(host){host.onclick=async e=>{
  const place=e.target.closest('[data-district]');if(place){district=place.dataset.district;host.querySelectorAll('[data-district]').forEach(b=>{b.classList.toggle('selected',b===place);b.setAttribute('aria-pressed',String(b===place))});panel();document.getElementById('district-panel').focus({preventScroll:true});return;}
  const b=e.target.closest('[data-choice]');if(!b||busy)return;
  const key=b.dataset.key,item=current.items.find(r=>r.key===key)||current.choices[key];if(!item)return;
  busy=true;b.disabled=true;
  try{await root.Campaign.save(key,{choice:b.dataset.choice,name:item.name,annual:Math.round(item.annual),updated_at:new Date().toISOString()},current.choices[key]||null);const toast=document.getElementById('campaign-toast');toast.textContent=b.dataset.choice==='requested'?'Demande notée. Son effet sera à vérifier sur les prochains relevés.':b.dataset.choice?'Un choix de plus. Ton territoire avance !':'Choix rouvert.';toast.hidden=false;toast.classList.remove('celebrate');void toast.offsetWidth;toast.classList.add('celebrate');}
  catch(err){const toast=document.getElementById('campaign-toast');toast.textContent=err.message;toast.hidden=false;}
  finally{busy=false;b.disabled=false;setTimeout(()=>{const toast=document.getElementById('campaign-toast');if(toast)toast.hidden=true},6000);}
 };}
 root.Campaign={model,render,route,save:async()=>{throw Error('Connexion indisponible. Réessaie après actualisation.')}};
 if(typeof addEventListener!=='undefined')addEventListener('hashchange',route);
 if(typeof module!=='undefined')module.exports=root.Campaign;
})(typeof window==='undefined'?{}:window);
